apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: '*'
      helm:
        valueFiles:
          - $values/kps-values.yaml
        values: |
          crds:
            enabled: true
    - repoURL: https://github.com/fk36dks/Final-PJ.git
      targetRevision: main
      ref: values
      path: manifests/monitoring/values
    - repoURL: https://github.com/fk36dks/Final-PJ.git
      targetRevision: main
      path: manifests/monitoring/values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

