apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finalproject-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fk36dks/FinalProject.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: finalproject-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

