# manifests/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
  namespace: shop
  labels:
    app: shop-backend
spec:
  # ✅ 롤링 중 가용성 보장 강화
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  minReadySeconds: 5
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
        - name: shop-backend
          image: 335507813633.dkr.ecr.ap-northeast-2.amazonaws.com/shop-backend:63
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            # 필요시 환경변수 추가 (예: RDS/Redis)
            # - name: DATABASE_URL
            #   value: ...
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "700m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
      terminationGracePeriodSeconds: 30

