apiVersion: v1
kind: Service
metadata:
  name: shop-frontend
  namespace: finalproject-dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing  # 퍼블릭 LB
spec:
  type: LoadBalancer
  selector:
    app: shop-frontend
  ports:
    - port: 80
      targetPort: 80

