apiVersion: v1
kind: Service
metadata:
  name: shop-frontend
  namespace: shop
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: ClusterIP
  selector:
    app: shop-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80

