apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'slack-default'
      group_by: ['alertname', 'namespace', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
      - matchers:
        - severity="critical"
        receiver: slack-critical
      - matchers:
        - severity="warning"
        receiver: slack-warning

    receivers:
    - name: 'slack-default'
      slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack-webhook/url
        channel: '#alert-manage'
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} ({{ or .CommonLabels.severity "n/a" }})
        text: |-
          *Namespace:* {{ or .CommonLabels.namespace "n/a" }}
          *Summary:* {{ or .CommonAnnotations.summary .CommonLabels.alertname }}
          *Description:* {{ or .CommonAnnotations.description "n/a" }}
          {{- range .Alerts }}
          • *Alert:* {{ .Labels.alertname }} | *Starts:* {{ .StartsAt }} | *Ends:* {{ .EndsAt }}
          {{- end }}
          *Labels:* {{ .CommonLabels }}

    - name: 'slack-critical'
      slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack-webhook/url
        channel: '#alert-manage'
        send_resolved: true
        title: "🚨 CRITICAL: {{ .CommonLabels.alertname }}"
        text: |-
          {{- range .Alerts }}
          • {{ or .Annotations.description "n/a" }}
          {{- end }}

    - name: 'slack-warning'
      slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack-webhook/url
        channel: '#alert-manage'
        send_resolved: true
        title: "⚠️ WARNING: {{ .CommonLabels.alertname }}"
        text: |-
          {{- range .Alerts }}
          • {{ or .Annotations.description "n/a" }}
          {{- end }}


